#!/bin/bash
#
# unban all banned websites
#
# broken: https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac

sudo sed -i '' 's/1.1.1.1*/#&/g' /etc/hosts
sudo dscacheutil -flushcache

